/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as MonCompteRouteImport } from './routes/mon-compte'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const MonCompteRoute = MonCompteRouteImport.update({
  id: '/mon-compte',
  path: '/mon-compte',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mon-compte': typeof MonCompteRoute
  '/reservation': typeof ReservationRoute
  '/services': typeof ServicesRoute
  '/vitrine': typeof VitrineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mon-compte': typeof MonCompteRoute
  '/reservation': typeof ReservationRoute
  '/services': typeof ServicesRoute
  '/vitrine': typeof VitrineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mon-compte': typeof MonCompteRoute
  '/reservation': typeof ReservationRoute
  '/services': typeof ServicesRoute
  '/vitrine': typeof VitrineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mon-compte'
    | '/reservation'
    | '/services'
    | '/vitrine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/mon-compte' | '/reservation' | '/services' | '/vitrine'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/mon-compte'
    | '/reservation'
    | '/services'
    | '/vitrine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MonCompteRoute: typeof MonCompteRoute
  ReservationRoute: typeof ReservationRoute
  ServicesRoute: typeof ServicesRoute
  VitrineRoute: typeof VitrineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-compte': {
      id: '/mon-compte'
      path: '/mon-compte'
      fullPath: '/mon-compte'
      preLoaderRoute: typeof MonCompteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MonCompteRoute: MonCompteRoute,
  ReservationRoute: ReservationRoute,
  ServicesRoute: ServicesRoute,
  VitrineRoute: VitrineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
